import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './global.css';
import { CartProvider } from "@/context/cart";
import { MenuProvider } from "@/context/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MKS STORE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
        <MenuProvider>
        {children}
        </MenuProvider>
        </CartProvider></body>
    </html>
  );
}
